local color = require('chameleon.colors').palette

return {
  DevIconDefault = { fg = color.red },
  DevIconc = { fg = color.blue },
  DevIconcss = { fg = color.blue },
  DevIcondeb = { fg = color.cyan },
  DevIconDockerfile = { fg = color.cyan },
  DevIconhtml = { fg = color.baby_pink },
  DevIconjpeg = { fg = color.magenta },
  DevIconjpg = { fg = color.magenta },
  DevIconjs = { fg = color.yellow },
  DevIconkt = { fg = color.orange },
  DevIconlock = { fg = color.red },
  DevIconlua = { fg = color.blue },
  DevIconmp3 = { fg = color.white },
  DevIconmp4 = { fg = color.white },
  DevIconout = { fg = color.white },
  DevIconpng = { fg = color.magenta },
  DevIconpy = { fg = color.cyan },
  DevIcontoml = { fg = color.blue },
  DevIconts = { fg = color.teal },
  DevIconttf = { fg = color.white },
  DevIconrb = { fg = color.pink },
  DevIconrpm = { fg = color.orange },
  DevIconvue = { fg = color.vibrant_green },
  DevIconwoff = { fg = color.white },
  DevIconwoff2 = { fg = color.white },
  DevIconxz = { fg = color.yellow },
  DevIconzip = { fg = color.yellow },
  DevIconZig = { fg = color.orange },
  DevIconMd = { fg = color.blue },
  DevIconTSX = { fg = color.blue },
  DevIconJSX = { fg = color.blue },
  DevIconSvelte = { fg = color.red },
  DevIconJava = { fg = color.orange },
  DevIconDart = { fg = color.cyan },
}
